version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 9229:9229
    develop:
      watch:
        - path: .
          action: rebuild
        - path: .
          target: /app
          action: sync
    # environment:
    #   - API_KEY=
    volumes:
      - ./:/app
      - /tmp:/tmp
